import React, { useState } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  TextField,
  MenuItem,
  Typography,
  Box,
  Alert,
  CircularProgress,
  Divider
} from '@mui/material';
import { Badge as BadgeIcon } from '@mui/icons-material';

const GeneratePassDialog = ({ open, onClose, onSuccess }) => {
  const [passType, setPassType] = useState('hiring_manager');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const passTypes = [
    { value: 'hiring_manager', label: 'Hiring Manager Pass' },
    { value: 'candidate', label: 'Candidate Pass' },
    { value: 'employee', label: 'Employee Pass' },
    { value: 'manager', label: 'Manager Pass (3-in-1)' }
  ];

  const handleGenerate = async () => {
    setLoading(true);
    setError('');

    try {
      // TODO: Implement pass generation
      await new Promise(resolve => setTimeout(resolve, 1000));
      onSuccess();
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
      <DialogTitle>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <BadgeIcon />
          <Typography variant="h6">Generate Access Pass</Typography>
        </Box>
      </DialogTitle>

      <Divider />

      <DialogContent sx={{ pt: 3 }}>
        {error && (
          <Alert severity="error" sx={{ mb: 3 }} onClose={() => setError('')}>
            {error}
          </Alert>
        )}

        <Alert severity="info" sx={{ mb: 3 }}>
          Passes are invitations/access tokens generated by HR. Recipients receive a unique link to access their portal.
        </Alert>

        <TextField
          select
          fullWidth
          label="Pass Type"
          value={passType}
          onChange={(e) => setPassType(e.target.value)}
          sx={{ mb: 2 }}
        >
          {passTypes.map((type) => (
            <MenuItem key={type.value} value={type.value}>
              {type.label}
            </MenuItem>
          ))}
        </TextField>

        <Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>
          Pass generation functionality coming soon...
        </Typography>
      </DialogContent>

      <Divider />

      <DialogActions sx={{ p: 2 }}>
        <Button onClick={onClose} disabled={loading}>
          Cancel
        </Button>
        <Button
          variant="contained"
          onClick={handleGenerate}
          disabled={loading}
          sx={{ background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)' }}
        >
          {loading ? <CircularProgress size={24} color="inherit" /> : 'Generate Pass'}
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default GeneratePassDialog;
